services:
  - type: web
    name: fraud-detection-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: BASE_DIR
        value: /app
      - key: MODEL_DATA_DIR
        value: /app/Data/Model_Data
      - key: SKLEARN_MODEL_PATH
        value: /app/Models/gbt_sklearn.pkl
